# This rule is not used by the project go-assesstment itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over deskree.platform.deskree.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-assesstment
    app.kubernetes.io/managed-by: kustomize
  name: appdeployment-admin-role
rules:
- apiGroups:
  - deskree.platform.deskree.com
  resources:
  - appdeployments
  verbs:
  - '*'
- apiGroups:
  - deskree.platform.deskree.com
  resources:
  - appdeployments/status
  verbs:
  - get
